// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users_queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const fetchUser = `-- name: FetchUser :one
    SElECT user_id, username, password_hash, email, ip_address FROM Users WHERE
    user_id = $1 LIMIT 1
`

func (q *Queries) FetchUser(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, fetchUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.IpAddress,
	)
	return i, err
}
